name: enlightened-rep

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  refresh-and-log:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Refresh and log enlightened rep
        run: python wowguilds/runners/enlightened-rep.py
