name: enlightened-rep

env:
  DEFAULT_REGION: eu
  DEFAULT_REALM: Nemesis
  DEFAULT_GUILD: IgnorHunters

on:
  # Allows you to run this workflow manually from the Actions tab. https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch:
    inputs:
      region:
        type: string
        required: true
        default: eu
        description: Region (eu/na)
      realm:
        type: string
        required: true
        default: Nemesis
        description: Realm
      guild:
        type: string
        required: true
        default: IgnorHunters
        description: Guild
  schedule:
    - cron: '0 6 * * *'

jobs:
  refresh-and-log:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install .
      - name: Refresh and log enlightened rep
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: |
        python -m wowguilds.runners.enlightened_rep
        --region '${{ github.event.inputs.region || env.DEFAULT_REGION }}'
        --realm '${{ github.event.inputs.realm || env.DEFAULT_REALM }}'
        --guild '${{ github.event.inputs.guild || env.DEFAULT_GUILD }}'
        --refresh
