name: enlightened-rep

on:
  # Allows you to run this workflow manually from the Actions tab. https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
  workflow_call:
    inputs:
      guild:
        type: string
        required: true
        default: IgnorHunters

jobs:
  refresh-and-log:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install .
      - name: Refresh and log enlightened rep
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: python -m wowguilds.runners.enlightened_rep --refresh --guild ${{ github.event.inputs.guild }}
